version: "3"
services:
  calibre:
    container_name: calibre
    image: ghcr.io/linuxserver/calibre-web
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_MODS: linuxserver/calibre-web:calibre  # optional & x86-64 only Adds the ability to perform ebook conversion
    volumes:
      - ./docker/calibre/config:/config
      - ${CALIBRE_BOOKS}:/books
    restart: always
    labels:
      - traefik.http.routers.calibre.rule=Host(`${CALIBRE_HOST}`)
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.certresolver=myresolver
      - traefik.http.middlewares.calibre.compress=true
      - traefik.http.services.calibre.loadbalancer.server.port=8083
      - traefik.http.routers.calibre.middlewares=calibre@docker
