version: "3"
services:
  icecoder:
    container_name: icecoder
    image: griefed/icecoder:latest
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - GITURL=${ICECODER_GITREPO} # GitHub Repository to clone during container creation
    volumes:
      - ${CONF_FOLDER}/icecoder/plugins:/plugins # Contains all installed plugins.
      - ${CONF_FOLDER}/icecoder/data:/data # Contains ICEcoder data like backups.
      - ${CONF_FOLDER}/icecoder/config:/config # Contains config files and logs.
      - ${CONF_FOLDER}/icecoder/code:/code # Contains GITURL repository.
    restart: always
    labels:
      - traefik.http.routers.icecoder.rule=Host(`${ICECODER_HOST}`)
      - traefik.http.routers.icecoder.tls=true
      - traefik.http.routers.icecoder.tls.certresolver=myresolver
      - traefik.http.middlewares.icecoder.compress=true
      - traefik.http.services.icecoder.loadbalancer.server.port=8080
      - traefik.http.routers.icecoder.middlewares=icecoder@docker

  cloud9:
    container_name: cloud9
    image: ghcr.io/linuxserver/cloud9
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GITURL=${CLOUD9_GITREPO}
      - USERNAME=${CLOUD9_USER} #optional
      - PASSWORD=${CLOUD9_PASS} #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
    restart: always
    labels:
      - traefik.http.routers.cloud9.rule=Host(`${CLOUD9_HOST}`)
      - traefik.http.routers.cloud9.tls=true
      - traefik.http.routers.cloud9.tls.certresolver=myresolver
      - traefik.http.middlewares.cloud9.compress=true
      - traefik.http.services.cloud9.loadbalancer.server.port=8000
      - traefik.http.routers.cloud9.middlewares=cloud9@docker

  code-server:
    container_name: code-server
    image: ghcr.io/linuxserver/code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CODESERVER_PASS} #optional
      - SUDO_PASSWORD=${CODESERVER_SUDO_PASS} #optional
      - PROXY_DOMAIN=${CODESERVER_PROXY_DOMAIN} #optional
    volumes:
      - ${CONF_FOLDER}/code-server:/config
    restart: always
    labels:
      - traefik.http.routers.code-server.rule=Host(`${CODESERVER_HOST}`)
      - traefik.http.routers.code-server.tls=true
      - traefik.http.routers.code-server.tls.certresolver=myresolver
      - traefik.http.middlewares.code-server.compress=true
      - traefik.http.services.code-server.loadbalancer.server.port=8443
      - traefik.http.routers.code-server.middlewares=code-server@docker
