version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      TZ: ${TZ}
    volumes:
      - ${CONF_FOLDER}/home-assistant/config:/config
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8480:8123/tcp
    restart: unless-stopped
    labels:
      - traefik.http.routers.homeassistant.rule=Host(`${HOMEASSISTANT_HOST}`)
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=myresolver
      - traefik.http.middlewares.homeassistant.compress=true
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.http.routers.homeassistant.middlewares=homeassistant@docker
