version: "3"
services:
  logspout:
    container_name: logspout
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog+tcp://${LOGSTASH_SERVER}:5000
    restart: always
    labels:
      - traefik.enable=false