version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK_SET: ${UMASK_SET} #optional
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
    devices:
      # - /dev/dri:/dev/dri #optional
    volumes:
      - ${DATA_FOLDER}/plex/library:/config
      - ${TV_SERIES_DIR}:/tv
      - ${MOVIES_DIR}:/movies
    hostname: ${PLEX_HOST}
    ports:
     - 32400:32400/tcp
     - 32400:32400/udp
     - 3005:3005/tcp
     - 8324:8324/tcp
     - 32469:32469/tcp
     - 1900:1900/udp
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
    restart: always
    labels:
      - traefik.http.routers.plex.rule=Host(`${PLEX_HOST}`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=myresolver
      - traefik.http.middlewares.plex.compress=true
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.middlewares=plex@docker

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK: ${UMASK_SET} #optional
    volumes:     
      - ${DATA_FOLDER}/jellyfin/library:/config
      # - /opt/vc/lib:/opt/vc/lib #optional
      - ${TV_SERIES_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1901:1900/udp #optional
    devices:
      # - /dev/dri:/dev/dri #optional
      # - /dev/video0:/dev/video0 #optional
      # - /dev/video1:/dev/video1 #optional
    restart: always
    labels:
      - traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOST}`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=myresolver
      - traefik.http.middlewares.jellyfin.compress=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.middlewares=jellyfin@docker
