version: "3"
services:
  hedgedoc_db:
    container_name: hedgedoc_db
    image: ghcr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - ${CONF_FOLDER}/hedgedoc/db/:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${HEDGEDOC_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${HEDGEDOC_MYSQL_DATABASE}
      - MYSQL_USER=${HEDGEDOC_MYSQL_USER}
      - MYSQL_PASSWORD=${HEDGEDOC_MYSQL_PASSWORD}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
  hedgedoc:
    container_name: hedgedoc
    image: ghcr.io/linuxserver/hedgedoc:latest
    depends_on:
      - hedgedoc_db
    volumes:
      - ${CONF_FOLDER}/hedgedoc/config:/config
    environment:
      - DB_HOST=hedgedoc_db
      - DB_USER=${HEDGEDOC_MYSQL_USER}
      - DB_PASS=${HEDGEDOC_MYSQL_PASSWORD}
      - DB_NAME=${HEDGEDOC_MYSQL_DATABASE}
      - DB_PORT=3306
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      - traefik.http.routers.codimd.rule=Host(`${HEDGEDOC_HOST}`)
      - traefik.http.routers.codimd.tls=true
      - traefik.http.routers.codimd.tls.certresolver=myresolver
      - traefik.http.middlewares.codimd.compress=true
      - traefik.http.services.codimd.loadbalancer.server.port=3000
      - traefik.http.routers.codimd.middlewares=codimd@docker

  wekan_db:
    image: quay.io/wekan/mongo:4.4.2-bionic
    container_name: wekan_db
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    expose:
      - 27017
    volumes:
      - ${CONF_FOLDER}/wekan/db:/data/db
      - ${CONF_FOLDER}/wekan/db-dump:/dump
    labels:
      - traefik.enable=false
  wekan:
    container_name: wekan
    image: quay.io/wekan/wekan
    environment:
      MONGO_URL: mongodb://wekan_db:27017/wekan
      ROOT_URL: ${WEKAN_ROOT_URL}  #   <=== using only at same laptop/desktop where Wekan is installed
      MAIL_URL: ${WEKAN_MAIL_URL}
      MAIL_FROM: ${WEKAN_MAIL_FROM}
      WITH_API: 'true'
      RICHER_CARD_COMMENT_EDITOR: 'true'
      CARD_OPENED_WEBHOOK_ENABLED: 'false'
      BIGEVENTS_PATTERN: 'NONE'
      BROWSER_POLICY_ENABLED: 'true'
    depends_on:
      - wekan_db
    restart: unless-stopped
    labels:
      - traefik.http.routers.wekan.rule=Host(`${WEKAN_HOST}`)
      - traefik.http.routers.wekan.tls=true
      - traefik.http.routers.wekan.tls.certresolver=myresolver
      - traefik.http.middlewares.wekan.compress=true
      - traefik.http.services.wekan.loadbalancer.server.port=8080
      - traefik.http.routers.wekan.middlewares=wekan@docker

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # GUAC_USER: ${CALIBRE_USER} #optional
      # GUAC_PASS: ${CALIBRE_PASS} #optional
      UMASK_SET: ${UMASK_SET}
      # CLI_ARGS: #optional
    volumes:
      - ${CONF_FOLDER}/calibre/data:/config
      - ${CALIBRE_BOOKS}:/books
      - ${CALIBRE_LIBRARY}:/library # Must be an empty folder or and old Calibre library
    ports:
      - 8080:8080 # Calibre Gui port
    restart: unless-stopped
    labels:
      - traefik.http.routers.calibre.rule=Host(`${CALIBRE_HOST}`)
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.certresolver=myresolver
      - traefik.http.middlewares.calibre.compress=true
      - traefik.http.services.calibre.loadbalancer.server.port=8081
      - traefik.http.routers.calibre.middlewares=calibre@docker

  firefox:
    container_name: firefox
    image: jlesage/firefox
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${CONF_FOLDER}/firefox/config:/config:rw
    restart: unless-stopped
    labels:
      - traefik.http.routers.firefox.rule=Host(`${FIREFOX_HOST}`)
      - traefik.http.routers.firexox.tls=true
      - traefik.http.routers.firefox.tls.certresolver=myresolver
      - traefik.http.middlewares.firefox.compress=true
      - traefik.http.services.firefox.loadbalancer.server.port=5800
      - traefik.http.routers.firefox.middlewares=firefox@docker
