version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    user: root
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PWD}
      ServerIp: ${PIHOLE_IP}
      IPv6: 'false'
    volumes:
      - ./${PIHOLE_FOLDER}/etc:/etc/pihole
      - ./${PIHOLE_FOLDER}/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - '8080:80/tcp'
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
