version: '3'
services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "nginx_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${NGINX_DB_USER}
      DB_MYSQL_PASSWORD: ${NGINX_DB_PASS}
      DB_MYSQL_NAME: ${NGINX_DB_NAME}
    volumes:
      - ${CONF_FOLDER}/nginx/data:/data
      - ${CONF_FOLDER}/nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  nginx_db:
    container_name: nginx_db
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${NGINX_DB_ROOT_PASS}
      MYSQL_DATABASE: ${NGINX_DB_NAME}
      MYSQL_USER: ${NGINX_DB_USER}
      MYSQL_PASSWORD: ${NGINX_DB_PASS}
    volumes:
      - ${CONF_FOLDER}/nginx/db/mysql:/var/lib/mysql
    restart: always

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONF_FOLDER}/heimdall/config:/config
    ports:
      - 1080:80/tcp
    restart: always

  no-ip:
    container_name: no-ip
    image: coppit/no-ip
    user: ${PUID}:${PGID}
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CONF_FOLDER}/no-ip:/config
    restart: always

  ovh-dns:
    container_name: ovh-dns
    image: linuxserver/ddclient
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONF_FOLDER}/ovh-dns/config:/config
    restart: always

  jobber:
    container_name: jobber
    image: jobber
    environment:
      PUID: ${ROOT_ID}
      PGID: ${ROOT_ID}
      TZ: ${TZ}
    volumes:
      - ${CONF_FOLDER}:/DockerConf
      - ${DATA_FOLDER}:/DockerData
      - ${STORAGE}:/Storage
      - ${CONF_FOLDER}/jobber:/home/jobberuser
    restart: unless-stopped
