version: "3"
services:
  logspout:
    container_name: logspout
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog+tcp://${LOGSTASH_SERVER}:5000
    restart: always

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    command: -H unix:///var/run/docker.sock
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: my_secret_token_1234567890abcdef
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /portainer/volumes:/var/lib/docker/volumes
    ports:
      - '9001:9001/tcp'
    restart: always