version: "3"
services:
  samba:
    container_name: samba
    image: dperson/samba
    user: ${ROOT_ID}:${ROOT_ID}
    environment:
      TZ: ${TZ}
      NMBD: 'true'
      USER: ${SAMBA_USER_PASS}
#      USERID: '0'
#      GROUPID: '0'
      SAMBA_SHARE1: ${SAMBA_DOCKER_DATA}
      SAMBA_SHARE2: ${SAMBA_DATA}
      SAMBA_SHARE3: ${SAMBA_DIVX}
      WORKGROUP: ${SAMBA_WORKGROUP}
    stdin_open: true
    tty: true
    read_only: false
    volumes:
      - ${VOLUME_SAMBA}:/Samba
    ports:
      - '137:137/udp'
      - '138:138/udp'
      - '137:137/tcp'
      - '138:138/tcp'
      - '139:139/tcp'
      - '445:445/tcp'
    tmpfs:
      - /tmp
    restart: always