version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      user: ${ROOT_ID}:${ROOT_ID}
      TZ: ${TZ}
    volumes:
      - ${CONF_FOLDER}/home-assistant/config:/config
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - '7180:8123/tcp'
    restart: unless-stopped