version: "3"
services:
  openvpn:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # INTERFACE: eth0 #optional
    volumes:
      - ${CONF_FOLDER}/openvpn:/config
    ports:
      - 1043:943
      - 9443:9443
      - 1194:1194/udp
    restart: always
