version: '3'

services:

  vpn:
    container_name: vpn
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - '1194:1194/udp'
      - '1194:1194/tcp'

    environment:
      #  - VIRTUAL_PORT=${VIRTUAL_PORT_OPENVPN}
      #  - VIRTUAL_HOST=${VIRTUAL_HOST_OPENVPN}
      #  - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_VPN}
      #  - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      #  - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      #  - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      #  - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # - LOCAL_NETWORK=192.168.0.0/24
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 -   ^`^slog-driver json-file --log-opt max-size=10m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${CONF_FOLDER}/openvpn/data:/etc/openvpn
    networks:
      vpn-net:
        ipv4_address: ${OPENVPN_IP}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  pihole:
    image: pihole/pihole
    container_name: pihole
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    depends_on:
      - vpn
    ports:
      - '137:137/udp'
      - '138:138/udp'
      - '137:137/tcp'
      - '138:138/tcp'
      - '139:139/tcp'
      - '445:445/tcp'
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PWD}
      ServerIp: ${PIHOLE_IP}
      IPv6: 'false'
      DNS1: ${PIHOLE_DNS}
    volumes:
      - ${CONF_FOLDER}/pihole:/etc/pihole
      - ${CONF_FOLDER}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      vpn-net:
        ipv4_address: ${PIHOLE_IP}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: always

  samba:
    container_name: samba
    image: dperson/samba
    cap_add:
      - NET_ADMIN
    user: ${ROOT_ID}:${ROOT_ID}
    depends_on:
      - vpn
    environment:
      TZ: ${TZ}
      NMBD: 'true'
      USER: ${SAMBA_USER_PASS}
      SAMBA_SHARE1: ${SAMBA_TORRENT}
      SAMBA_SHARE2: ${SAMBA_FORMATION}
      WORKGROUP: ${SAMBA_WORKGROUP}
    stdin_open: true
    tty: true
    read_only: false
    volumes:
      - ${DATA_FOLDER}/${GDRIVE_FOLDER}:/GDrive
    networks:
      vpn-net:
        ipv4_address: ${SAMBA_IP}
    tmpfs:
      - /tmp
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    depends_on:
      - vpn
    environment:
      AGENT_SECRET: my_secret_token_1234567890abcdef
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONF_FOLDER}/portainer/volumes:/var/lib/docker/volumes
    networks:
      vpn-net:
        ipv4_address: ${PORTAINER_IP} #Port 9000
    restart: always

  ##################### NORDVPN #####################

  nordvpn:
    image: bubuntux/nordvpn:3.7.4
    container_name: nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=${VPN_USER}
      - PASS=${VPN_PASS}
      - CONNECT=${VPN_COUNTRY}
      - TECHNOLOGY=NordLynx
    extra_hosts:
      - "w569ut7zbkiqf5b.xyz:104.28.28.105"
      - "zwyr157wwiu6eior.com:104.17.188.107"
      - "boi9osyg1uwtyafn.com:104.16.229.42"

  torrent:
    image: linuxserver/qbittorrent
    container_name: torrent
    user: ${ROOT_ID}:${ROOT_ID}
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
    environment:
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=9091
    volumes:
      - ${CONF_FOLDER}/${TORRENT_BASE_DIR}/config:/config
      - ${DATA_FOLDER}/${GDRIVE_FOLDER}/${TORRENT_BASE_DIR}/downloads:/downloads
      - ${DATA_FOLDER}/${GDRIVE_FOLDER}/${TORRENT_BASE_DIR}/incomplete:/incomplete
      - ${DATA_FOLDER}/${GDRIVE_FOLDER}/${TORRENT_BASE_DIR}/torrents:/torrents

  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    container_name: web
    links:
      - nordvpn:torrent
      - vpn:pihole
    depends_on:
      - torrent
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    command: -w "http://torrent:9091/;/"

networks:
  vpn-net:
    external: true

# docker network create --driver=bridge --subnet=172.20.0.0/24 --gateway=172.20.0.1 vpn-net