version: "3"
services:
  vpn:
    image: bubuntux/nordvpn:3.7.4
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=${VPN_USER}
      - PASS=${VPN_PASS}
      - CONNECT=${VPN_COUNTRY}
      - TECHNOLOGY=NordLynx
    extra_hosts:
      - "w569ut7zbkiqf5b.xyz:104.28.28.105"
      - "zwyr157wwiu6eior.com:104.17.188.107"
      - "boi9osyg1uwtyafn.com:104.16.229.42"
    restart: unless-stopped


  torrent:
    image: linuxserver/qbittorrent
    container_name: torrent
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
      - WEBUI_PORT=9091
    volumes:
      - ${TORRENT_BASE_DIR}/config:/config
      - ${TORRENT_BASE_DIR}/downloads:/downloads
      - ${TORRENT_BASE_DIR}/incomplete:/incomplete
      - ${TORRENT_BASE_DIR}/torrents:/torrents
    restart: unless-stopped

  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    container_name: web
    links:
      - vpn:torrent
    depends_on:
      - torrent
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    ports:
      - 80:80
      - 443:443
    command: -w "http://torrent:9091/;/"
    restart: unless-stopped